# -*- coding: utf-8 -*-
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Deleting model 'TvChannels'
        db.delete_table('hot_spot_tv_channels')

        # Deleting model 'TvForecastSources'
        db.delete_table('hot_spot_tv_forecast_sources')

        # Deleting model 'TvForecast'
        db.delete_table('hot_spot_tv_forecast')


    def backwards(self, orm):
        # Adding model 'TvChannels'
        db.create_table('hot_spot_tv_channels', (
            ('channel_name', self.gf('django.db.models.fields.CharField')(max_length=300)),
            ('channel_name_eng', self.gf('django.db.models.fields.CharField')(max_length=300)),
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('channel_image', self.gf('django.db.models.fields.files.ImageField')(max_length=100, null=True)),
        ))
        db.send_create_signal(u'hotspot', ['TvChannels'])

        # Adding model 'TvForecastSources'
        db.create_table('hot_spot_tv_forecast_sources', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('name', self.gf('django.db.models.fields.CharField')(max_length=100)),
        ))
        db.send_create_signal(u'hotspot', ['TvForecastSources'])

        # Adding model 'TvForecast'
        db.create_table('hot_spot_tv_forecast', (
            ('time_minute', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('source', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['hotspot.TvForecastSources'])),
            ('description', self.gf('django.db.models.fields.CharField')(max_length=2000, null=True)),
            ('time_hour', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('date', self.gf('django.db.models.fields.DateTimeField')()),
            ('date_get', self.gf('django.db.models.fields.DateTimeField')()),
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('channel', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['hotspot.TvChannels'])),
            ('name', self.gf('django.db.models.fields.CharField')(max_length=500)),
        ))
        db.send_create_signal(u'hotspot', ['TvForecast'])


    models = {
        u'billing.billserviceaccount': {
            'Meta': {'object_name': 'BillserviceAccount', 'db_table': "u'billservice_account'"},
            'address': ('django.db.models.fields.TextField', [], {'default': "''"}),
            'allow_expresscards': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'allow_webcab': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'assigned_to': ('django.db.models.fields.IntegerField', [], {}),
            'auto_paid': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'balance_blocked': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'ballance': ('django.db.models.fields.DecimalField', [], {'default': "'0'", 'max_digits': '14', 'decimal_places': '2'}),
            'city': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'comment': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'contactperson': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'contactperson_phone': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'contract': ('django.db.models.fields.TextField', [], {}),
            'created': ('django.db.models.fields.DateTimeField', [], {}),
            'credit': ('django.db.models.fields.DecimalField', [], {'default': "'0'", 'max_digits': '20', 'decimal_places': '2'}),
            'disabled_by_limit': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'elevator_direction': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'email': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '200'}),
            'entrance': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'fullname': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '200'}),
            'group_id': ('django.db.models.fields.IntegerField', [], {'default': '1'}),
            'house': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'house_bulk': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'idle_time': ('django.db.models.fields.IntegerField', [], {'default': '4'}),
            'idle_time_for_every_month': ('django.db.models.fields.IntegerField', [], {'default': '15'}),
            'idle_time_for_internet': ('django.db.models.fields.IntegerField', [], {'default': '4'}),
            'notification_balance': ('django.db.models.fields.IntegerField', [], {'default': '50'}),
            'passport': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'passport_date': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'passport_given': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'password': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '200'}),
            'phone_h': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'phone_m': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'postcode': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'prices_group_id': ('django.db.models.fields.IntegerField', [], {'default': '1'}),
            'region': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'room': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'row': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'status': ('django.db.models.fields.IntegerField', [], {}),
            'street': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'suspended': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'username': ('django.db.models.fields.CharField', [], {'max_length': '200'}),
            'vlan': ('django.db.models.fields.IntegerField', [], {})
        },
        u'data_centr.price': {
            'Meta': {'object_name': 'Price'},
            'cost': ('django.db.models.fields.FloatField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'})
        },
        u'data_centr.service_type': {
            'Meta': {'object_name': 'Service_type'},
            'about': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'service': ('django.db.models.fields.CharField', [], {'max_length': '75'})
        },
        u'data_centr.tariff': {
            'Meta': {'object_name': 'Tariff'},
            'about': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'archive': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'billing_tariff': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['internet.Tariff']", 'null': 'True', 'blank': 'True'}),
            'cpu': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'depth': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'electricity': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'equipment': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True', 'blank': 'True'}),
            'for_person': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'to': u"orm['internet.Internet_persons_for_connection']", 'null': 'True', 'blank': 'True'}),
            'free_minutes': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'garant': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'hdd': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'height': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'individual': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'ip': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'port': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'price_id': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['data_centr.Price']"}),
            'ram': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'section_type': ('django.db.models.fields.IntegerField', [], {'default': '1'}),
            'service_type': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['data_centr.Service_type']"}),
            'socket': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'speed_inet': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tel_zone': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'tower_casing': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'unit': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'width': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'hotspot.activesession': {
            'Meta': {'object_name': 'ActiveSession', 'db_table': "'radius_activesession'", 'managed': 'False'},
            'account': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'hotspot_activesession_acc'", 'null': 'True', 'to': u"orm['billing.BillserviceAccount']"}),
            'acct_terminate_cause': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '128', 'blank': 'True'}),
            'bytes_in': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'bytes_out': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'caller_id': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'date_end': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'date_start': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'framed_ip_address': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '255', 'blank': 'True'}),
            'framed_protocol': ('django.db.models.fields.CharField', [], {'max_length': '32'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'interrim_update': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'null': 'True', 'blank': 'True'}),
            'nas_id': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'nas_int': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'hotspot_nas'", 'null': 'True', 'to': u"orm['hotspot.Nas']"}),
            'session_status': ('django.db.models.fields.CharField', [], {'max_length': '32', 'null': 'True', 'blank': 'True'}),
            'session_time': ('django.db.models.fields.IntegerField', [], {}),
            'sessionid': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'speed_string': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True', 'blank': 'True'}),
            'subaccount': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'hotspot_activesession_sub'", 'null': 'True', 'to': u"orm['internet.SubAccount']"})
        },
        u'hotspot.comments_of_video': {
            'Meta': {'object_name': 'Comments_Of_Video', 'db_table': "'hotspot_video_comments'"},
            'add_to_site': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'comment_content': ('django.db.models.fields.CharField', [], {'max_length': '5000'}),
            'commentator_name': ('django.db.models.fields.CharField', [], {'max_length': '300'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        u'hotspot.districtadministration': {
            'Meta': {'object_name': 'DistrictAdministration', 'db_table': "'district_administration'"},
            'add_information': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'adress': ('django.db.models.fields.CharField', [], {'max_length': '512'}),
            'email': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'fax': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '512'}),
            'prefecturs': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['hotspot.Prefecturs']", 'null': 'True', 'blank': 'True'}),
            'subway_station': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'tel_numbers': ('django.db.models.fields.CharField', [], {'max_length': '512'}),
            'web_site': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'x': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'y': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'})
        },
        u'hotspot.games': {
            'Meta': {'ordering': "['game_name']", 'object_name': 'Games'},
            'banner': ('django.db.models.fields.TextField', [], {}),
            'description': ('django.db.models.fields.TextField', [], {}),
            'game_name': ('django.db.models.fields.CharField', [], {'max_length': '200'}),
            'http': ('django.db.models.fields.CharField', [], {'max_length': '200'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'img': ('django.db.models.fields.CharField', [], {'max_length': '200'}),
            'section': ('django.db.models.fields.CharField', [], {'max_length': '200', 'null': 'True', 'blank': 'True'}),
            'section2': ('django.db.models.fields.CharField', [], {'max_length': '200', 'null': 'True', 'blank': 'True'}),
            'section_game': ('django.db.models.fields.related.ManyToManyField', [], {'default': '1', 'to': u"orm['hotspot.Games_Section']", 'symmetrical': 'False'})
        },
        u'hotspot.games_section': {
            'Meta': {'object_name': 'Games_Section'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '200'}),
            'short_name': ('django.db.models.fields.CharField', [], {'max_length': '200'})
        },
        u'hotspot.homeadministration': {
            'Meta': {'object_name': 'HomeAdministration', 'db_table': "'home_administration'"},
            'add_information': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'adress': ('django.db.models.fields.CharField', [], {'max_length': '512'}),
            'district_administration': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['hotspot.DistrictAdministration']", 'null': 'True', 'blank': 'True'}),
            'email': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'fax': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '512'}),
            'subway_station': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'tel_numbers': ('django.db.models.fields.CharField', [], {'max_length': '512'}),
            'web_site': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'x': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'y': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'})
        },
        u'hotspot.hotspot_bad_video_link': {
            'Meta': {'object_name': 'HotSpot_Bad_Video_Link', 'db_table': "'hot_spot_bad_video_link'"},
            'broken_video_id': ('django.db.models.fields.CharField', [], {'max_length': '400', 'null': 'True', 'blank': 'True'}),
            'contact_face': ('django.db.models.fields.CharField', [], {'max_length': '512', 'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'mail': ('django.db.models.fields.EmailField', [], {'max_length': '75', 'null': 'True', 'blank': 'True'}),
            'text': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'})
        },
        u'hotspot.hotspotquerystatistic': {
            'Meta': {'object_name': 'HotSpotQueryStatistic', 'db_table': "'hot_spot_query_statistic'"},
            'date_time': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'query_string': ('django.db.models.fields.CharField', [], {'max_length': '512', 'null': 'True', 'blank': 'True'})
        },
        u'hotspot.hotspotrate': {
            'Meta': {'object_name': 'HotSpotRate', 'db_table': "'hot_spot_rate'"},
            'char_code': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'date': ('django.db.models.fields.DateField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '512'}),
            'nominal': ('django.db.models.fields.IntegerField', [], {'max_length': '512'}),
            'value': ('django.db.models.fields.DecimalField', [], {'max_digits': '6', 'decimal_places': '2'})
        },
        u'hotspot.hotspotreview': {
            'Meta': {'object_name': 'HotSpotReview', 'db_table': "'hot_spot_review'"},
            'adres': ('django.db.models.fields.CharField', [], {'max_length': '512', 'null': 'True', 'blank': 'True'}),
            'contact_face': ('django.db.models.fields.CharField', [], {'max_length': '512', 'null': 'True', 'blank': 'True'}),
            'date': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'mail': ('django.db.models.fields.EmailField', [], {'max_length': '75'}),
            'telnumber': ('django.db.models.fields.CharField', [], {'max_length': '15', 'null': 'True', 'blank': 'True'}),
            'text': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'type': ('django.db.models.fields.CharField', [], {'max_length': '15', 'null': 'True', 'blank': 'True'}),
            'was_treated': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        },
        u'hotspot.hotspotweatger': {
            'Meta': {'object_name': 'HotSpotWeatger', 'db_table': "'hot_spot_weather'"},
            'date': ('django.db.models.fields.DateField', [], {'null': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'spr_class': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'temp_d_n': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'temp_now': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'title': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True'})
        },
        u'hotspot.ipinuse': {
            'Meta': {'object_name': 'IPInUse'},
            'datetime': ('django.db.models.fields.DateTimeField', [], {}),
            'disabled': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'dynamic': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'ip': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'pool': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['hotspot.IPPool']"})
        },
        u'hotspot.ippool': {
            'Meta': {'ordering': "['name']", 'object_name': 'IPPool'},
            'end_ip': ('django.db.models.fields.IPAddressField', [], {'max_length': '15'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'next_ippool': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['hotspot.IPPool']", 'null': 'True', 'blank': 'True'}),
            'start_ip': ('django.db.models.fields.IPAddressField', [], {'max_length': '15'}),
            'type': ('django.db.models.fields.IntegerField', [], {})
        },
        u'hotspot.mainnews': {
            'Meta': {'object_name': 'MainNews', 'db_table': "'hot_spot_main_news'"},
            'date_get_news': ('django.db.models.fields.DateField', [], {'auto_now_add': 'True', 'null': 'True', 'blank': 'True'}),
            'discription_news': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'img_news': ('django.db.models.fields.CharField', [], {'max_length': '1000', 'null': 'True', 'blank': 'True'}),
            'img_news_root': ('django.db.models.fields.CharField', [], {'max_length': '1000', 'null': 'True', 'blank': 'True'}),
            'link_news': ('django.db.models.fields.CharField', [], {'max_length': '1000', 'null': 'True', 'blank': 'True'}),
            'news_type': ('django.db.models.fields.CharField', [], {'max_length': '512', 'null': 'True', 'blank': 'True'}),
            'portal_copyright': ('django.db.models.fields.CharField', [], {'max_length': '512', 'null': 'True', 'blank': 'True'}),
            'portal_diskription': ('django.db.models.fields.CharField', [], {'max_length': '512', 'null': 'True', 'blank': 'True'}),
            'portal_link': ('django.db.models.fields.CharField', [], {'max_length': '512', 'null': 'True', 'blank': 'True'}),
            'portal_name': ('django.db.models.fields.CharField', [], {'max_length': '512', 'null': 'True', 'blank': 'True'}),
            'title_news': ('django.db.models.fields.CharField', [], {'max_length': '1000', 'null': 'True', 'blank': 'True'})
        },
        u'hotspot.mobiorganizationsunique': {
            'Meta': {'object_name': 'MobiOrganizationsUnique', 'db_table': "'hot_spot_mobi_organizations_unique'"},
            'address': ('django.db.models.fields.CharField', [], {'max_length': '300'}),
            'create_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'deleted': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'equal_coord_range': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'hours': ('django.db.models.fields.CharField', [], {'max_length': '300'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'location': ('django.db.models.fields.CharField', [], {'max_length': '300'}),
            'org_name': ('django.db.models.fields.CharField', [], {'max_length': '300'}),
            'org_type': ('django.db.models.fields.IntegerField', [], {}),
            'phone': ('django.db.models.fields.CharField', [], {'max_length': '300'}),
            'url': ('django.db.models.fields.CharField', [], {'max_length': '300'}),
            'x': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '16', 'decimal_places': '10', 'blank': 'True'}),
            'y': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '16', 'decimal_places': '10', 'blank': 'True'}),
            'yan_id': ('django.db.models.fields.IntegerField', [], {})
        },
        u'hotspot.mobiorganizationsuserchanges': {
            'Meta': {'object_name': 'MobiOrganizationsUserChanges', 'db_table': "'hot_spot_mobi_organization_user_changes'"},
            'applied': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'create_time': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'org_id': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['hotspot.MobiOrganizationsUnique']"}),
            'to_del': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'u_address': ('django.db.models.fields.CharField', [], {'max_length': '300', 'null': 'True', 'blank': 'True'}),
            'u_hours': ('django.db.models.fields.CharField', [], {'max_length': '300', 'null': 'True', 'blank': 'True'}),
            'u_org_name': ('django.db.models.fields.CharField', [], {'max_length': '300', 'null': 'True', 'blank': 'True'}),
            'u_phone': ('django.db.models.fields.CharField', [], {'max_length': '300', 'null': 'True', 'blank': 'True'}),
            'u_url': ('django.db.models.fields.CharField', [], {'max_length': '300', 'null': 'True', 'blank': 'True'}),
            'user_email': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True'}),
            'user_name': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True'})
        },
        u'hotspot.mobiweather': {
            'Meta': {'object_name': 'MobiWeather', 'db_table': "'hot_spot_mobi_weather'"},
            'city_weather_id': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['hotspot.WeatherCountries']", 'null': 'True', 'blank': 'True'}),
            'cloud': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'date_date_time': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'humidity': ('django.db.models.fields.FloatField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'pressure': ('django.db.models.fields.FloatField', [], {}),
            'source_name': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'taking_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'temp_from': ('django.db.models.fields.FloatField', [], {}),
            'temp_to': ('django.db.models.fields.FloatField', [], {}),
            'wind_dir': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'wind_speed': ('django.db.models.fields.FloatField', [], {})
        },
        u'hotspot.nas': {
            'Meta': {'object_name': 'Nas', 'db_table': "'nas_nas'"},
            'acct_interim_interval': ('django.db.models.fields.IntegerField', [], {'default': '60', 'null': 'True', 'blank': 'True'}),
            'allow_ipn': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'allow_pppoe': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'allow_pptp': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'confstring': ('django.db.models.fields.TextField', [], {'default': "''", 'blank': 'True'}),
            'data_centr_tarif': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['data_centr.Tariff']", 'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'identify': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'ipaddress': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'ipn_speed_action': ('django.db.models.fields.TextField', [], {'default': "''", 'max_length': '255', 'blank': 'True'}),
            'login': ('django.db.models.fields.CharField', [], {'default': "'admin'", 'max_length': '255', 'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'}),
            'password': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '255', 'blank': 'True'}),
            'reset_action': ('django.db.models.fields.TextField', [], {'default': "''", 'max_length': '255', 'blank': 'True'}),
            'secret': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'snmp_version': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'speed_attr_id1': ('django.db.models.fields.TextField', [], {'default': "''", 'blank': 'True'}),
            'speed_attr_id2': ('django.db.models.fields.TextField', [], {'default': "''", 'blank': 'True'}),
            'speed_value1': ('django.db.models.fields.TextField', [], {'default': "''", 'blank': 'True'}),
            'speed_value2': ('django.db.models.fields.TextField', [], {'default': "''", 'blank': 'True'}),
            'speed_vendor_1': ('django.db.models.fields.TextField', [], {'default': "''", 'blank': 'True'}),
            'speed_vendor_2': ('django.db.models.fields.TextField', [], {'default': "''", 'blank': 'True'}),
            'subacc_add_action': ('django.db.models.fields.TextField', [], {'default': "''", 'blank': 'True'}),
            'subacc_delete_action': ('django.db.models.fields.TextField', [], {'default': "''", 'blank': 'True'}),
            'subacc_disable_action': ('django.db.models.fields.TextField', [], {'default': "''", 'blank': 'True'}),
            'subacc_enable_action': ('django.db.models.fields.TextField', [], {'default': "''", 'blank': 'True'}),
            'subacc_ipn_speed_action': ('django.db.models.fields.TextField', [], {'default': "''", 'blank': 'True'}),
            'type': ('django.db.models.fields.CharField', [], {'default': "'mikrotik3'", 'max_length': '32'}),
            'user_add_action': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'user_delete_action': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'user_disable_action': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'user_enable_action': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'vpn_speed_action': ('django.db.models.fields.TextField', [], {'default': "''", 'max_length': '255', 'blank': 'True'})
        },
        u'hotspot.prefecturs': {
            'Meta': {'object_name': 'Prefecturs', 'db_table': "'prefecturs'"},
            'add_information': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'adress': ('django.db.models.fields.CharField', [], {'max_length': '512'}),
            'email': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'fax': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '512'}),
            'subway_station': ('django.db.models.fields.CharField', [], {'max_length': '512'}),
            'tel_numbers': ('django.db.models.fields.CharField', [], {'max_length': '512'}),
            'web_site': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'x': ('django.db.models.fields.CharField', [], {'max_length': '512'}),
            'y': ('django.db.models.fields.CharField', [], {'max_length': '512'})
        },
        u'hotspot.video': {
            'Meta': {'object_name': 'Video', 'db_table': "'hot_spot_video'"},
            'age_restrictions': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'budget': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'cast': ('django.db.models.fields.CharField', [], {'max_length': '600', 'blank': 'True'}),
            'comments_m2m': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'to': u"orm['hotspot.Comments_Of_Video']", 'null': 'True', 'blank': 'True'}),
            'country': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True'}),
            'date_aded': ('django.db.models.fields.DateTimeField', [], {'default': 'None', 'null': 'True', 'blank': 'True'}),
            'description': ('django.db.models.fields.CharField', [], {'max_length': '6000', 'blank': 'True'}),
            'director': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'genres': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'to': u"orm['hotspot.VideoGenre']", 'null': 'True', 'blank': 'True'}),
            'genres_client_view': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'id_gid_film': ('django.db.models.fields.CharField', [], {'max_length': '1000', 'unique': 'True', 'null': 'True', 'blank': 'True'}),
            'image_link': ('django.db.models.fields.CharField', [], {'max_length': '200', 'blank': 'True'}),
            'imdb_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'imdb_rating': ('django.db.models.fields.CharField', [], {'max_length': '600', 'null': 'True', 'blank': 'True'}),
            'internal_number': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'kp_rating': ('django.db.models.fields.CharField', [], {'max_length': '600', 'null': 'True', 'blank': 'True'}),
            'label_text': ('django.db.models.fields.CharField', [], {'default': '1', 'max_length': '50000', 'blank': 'True'}),
            'one_serial_links': ('django.db.models.fields.CharField', [], {'default': '1', 'max_length': '50000', 'blank': 'True'}),
            'orig_title': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True'}),
            'player_video_url': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '9200'}),
            'premiere_date': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'quality': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'rating': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'rating_by': ('django.db.models.fields.CharField', [], {'max_length': '1000', 'blank': 'True'}),
            'screenplay': ('django.db.models.fields.CharField', [], {'max_length': '600', 'blank': 'True'}),
            'site_rating': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['hotspot.Video_Rate']", 'null': 'True', 'blank': 'True'}),
            'sound': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'source': ('django.db.models.fields.IntegerField', [], {}),
            'time': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'title': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True'}),
            'translit_video_name': ('django.db.models.fields.CharField', [], {'max_length': '400', 'unique': 'True', 'null': 'True', 'blank': 'True'}),
            'video_type': ('django.db.models.fields.IntegerField', [], {'blank': 'True'}),
            'year': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'})
        },
        u'hotspot.video_rate': {
            'Meta': {'object_name': 'Video_Rate', 'db_table': "'rate_video'"},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'rating_score': ('django.db.models.fields.CharField', [], {'max_length': '300'}),
            'rating_votes': ('django.db.models.fields.CharField', [], {'max_length': '300'})
        },
        u'hotspot.videogenre': {
            'Meta': {'object_name': 'VideoGenre', 'db_table': "'hot_spot_video_genre'"},
            'genre': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'translit_genre': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'})
        },
        u'hotspot.weathercountries': {
            'Meta': {'object_name': 'WeatherCountries', 'db_table': "'hot_spot_weather_countries'"},
            'city_eng_name': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'city_rus_name': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'country_eng_name': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'country_rus_name': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'openweathermap_name': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'region_id': ('django.db.models.fields.IntegerField', [], {}),
            'yandex_city_id': ('django.db.models.fields.IntegerField', [], {})
        },
        u'internet.accessparameters': {
            'Meta': {'object_name': 'AccessParameters', 'db_table': "'billservice_accessparameters'"},
            'access_time': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['internet.TimePeriod']", 'null': 'True', 'on_delete': 'models.SET_NULL'}),
            'access_type': ('django.db.models.fields.CharField', [], {'default': "'PPTP'", 'max_length': '255', 'blank': 'True'}),
            'burst_rx': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '64', 'blank': 'True'}),
            'burst_time_rx': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '64', 'blank': 'True'}),
            'burst_time_tx': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '64', 'blank': 'True'}),
            'burst_treshold_rx': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '64', 'blank': 'True'}),
            'burst_treshold_tx': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '64', 'blank': 'True'}),
            'burst_tx': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '64', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'ipn_for_vpn': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'max_rx': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '64', 'blank': 'True'}),
            'max_tx': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '64', 'blank': 'True'}),
            'min_rx': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '64', 'blank': 'True'}),
            'min_tx': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '64', 'blank': 'True'}),
            'priority': ('django.db.models.fields.IntegerField', [], {'default': '8', 'blank': 'True'}),
            'sessionscount': ('django.db.models.fields.IntegerField', [], {'default': '0', 'blank': 'True'})
        },
        u'internet.internet_persons_for_connection': {
            'Meta': {'object_name': 'Internet_persons_for_connection', 'db_table': "'internet_persons_for_connection'"},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'persons': ('django.db.models.fields.CharField', [], {'max_length': '100'})
        },
        u'internet.ipinuse': {
            'Meta': {'ordering': "['ip']", 'object_name': 'IPInUse', 'db_table': "'billservice_ipinuse'"},
            'ack': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'datetime': ('django.db.models.fields.DateTimeField', [], {}),
            'disabled': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'dynamic': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'ip': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'pool': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['internet.IPPool']"})
        },
        u'internet.ippool': {
            'Meta': {'ordering': "['name']", 'object_name': 'IPPool', 'db_table': "'billservice_ippool'"},
            'end_ip': ('django.db.models.fields.GenericIPAddressField', [], {'max_length': '39'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'next_ippool': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['internet.IPPool']", 'null': 'True', 'blank': 'True'}),
            'start_ip': ('django.db.models.fields.GenericIPAddressField', [], {'max_length': '39'}),
            'type': ('django.db.models.fields.IntegerField', [], {})
        },
        u'internet.radiustraffic': {
            'Meta': {'object_name': 'RadiusTraffic', 'db_table': "'billservice_radiustraffic'"},
            'created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'null': 'True', 'blank': 'True'}),
            'deleted': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'direction': ('django.db.models.fields.IntegerField', [], {'default': '2', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'prepaid_direction': ('django.db.models.fields.IntegerField', [], {'default': '2', 'blank': 'True'}),
            'prepaid_value': ('django.db.models.fields.IntegerField', [], {'default': '0', 'blank': 'True'}),
            'reset_prepaid_traffic': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'rounding': ('django.db.models.fields.IntegerField', [], {'default': '0', 'blank': 'True'}),
            'tarification_step': ('django.db.models.fields.IntegerField', [], {'default': '1024', 'blank': 'True'})
        },
        u'internet.settlementperiod': {
            'Meta': {'ordering': "['name']", 'object_name': 'SettlementPeriod', 'db_table': "'billservice_settlementperiod'"},
            'autostart': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'length': ('django.db.models.fields.IntegerField', [], {'default': '0', 'null': 'True', 'blank': 'True'}),
            'length_in': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '255', 'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'}),
            'time_start': ('django.db.models.fields.DateTimeField', [], {})
        },
        u'internet.subaccount': {
            'Meta': {'ordering': "['-username']", 'object_name': 'SubAccount', 'db_table': "'billservice_subaccount'"},
            'account': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['billing.BillserviceAccount']", 'null': 'True', 'blank': 'True'}),
            'allow_addonservice': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'allow_dhcp': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'allow_dhcp_with_block': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'allow_dhcp_with_minus': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'allow_dhcp_with_null': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'allow_ipn_with_block': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'allow_ipn_with_minus': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'allow_ipn_with_null': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'allow_mac_update': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'allow_vpn_with_block': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'allow_vpn_with_minus': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'allow_vpn_with_null': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'associate_pppoe_ipn_mac': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'associate_pptp_ipn_ip': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'ipn_added': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'ipn_enabled': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'ipn_ip_address': ('django.db.models.fields.TextField', [], {'default': "'0.0.0.0'", 'null': 'True', 'blank': 'True'}),
            'ipn_ipinuse': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'subaccount_ipn_ipinuse_set'", 'null': 'True', 'on_delete': 'models.SET_NULL', 'to': u"orm['internet.IPInUse']"}),
            'ipn_ipv6_ip_address': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'ipn_mac_address': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '17', 'blank': 'True'}),
            'ipn_sleep': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'ipn_speed': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ipv4_ipn_pool': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'subaccount_ipn_ippool_set'", 'on_delete': 'models.SET_NULL', 'default': 'None', 'to': u"orm['internet.IPPool']", 'blank': 'True', 'null': 'True'}),
            'ipv4_vpn_pool': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'subaccount_vpn_ippool_set'", 'on_delete': 'models.SET_NULL', 'default': 'None', 'to': u"orm['internet.IPPool']", 'blank': 'True', 'null': 'True'}),
            'ipv6_vpn_pool': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'subaccount_ipv6_vpn_ippool_set'", 'on_delete': 'models.SET_NULL', 'default': 'None', 'to': u"orm['internet.IPPool']", 'blank': 'True', 'null': 'True'}),
            'nas_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'need_resync': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'password': ('django.db.models.fields.TextField', [], {'default': "''", 'blank': 'True'}),
            'sessionscount': ('django.db.models.fields.IntegerField', [], {'default': '0', 'blank': 'True'}),
            'speed': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'switch_port': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'text_password': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'username': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'vlan': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'vpn_ip_address': ('django.db.models.fields.IPAddressField', [], {'default': "'0.0.0.0'", 'max_length': '15', 'null': 'True', 'blank': 'True'}),
            'vpn_ipinuse': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'subaccount_vpn_ipinuse_set'", 'null': 'True', 'on_delete': 'models.SET_NULL', 'to': u"orm['internet.IPInUse']"}),
            'vpn_ipv6_ip_address': ('django.db.models.fields.GenericIPAddressField', [], {'max_length': '39', 'null': 'True', 'blank': 'True'}),
            'vpn_ipv6_ipinuse': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'subaccount_vpn_ipv6_ipinuse_set'", 'null': 'True', 'on_delete': 'models.SET_NULL', 'to': u"orm['internet.IPInUse']"}),
            'vpn_speed': ('django.db.models.fields.TextField', [], {'blank': 'True'})
        },
        u'internet.tariff': {
            'Meta': {'ordering': "['name']", 'object_name': 'Tariff', 'db_table': "'billservice_tariff'"},
            'access_parameters': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['internet.AccessParameters']", 'null': 'True', 'on_delete': 'models.SET_NULL', 'blank': 'True'}),
            'active': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'allow_ballance_transfer': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'allow_express_pay': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'allow_userblock': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'cost': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'deleted': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'description': ('django.db.models.fields.TextField', [], {'default': "''", 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'}),
            'ps_null_ballance_checkout': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'radius_traffic_transmit_service': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['internet.RadiusTraffic']", 'null': 'True', 'on_delete': 'models.SET_NULL', 'blank': 'True'}),
            'require_tarif_cost': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'reset_tarif_cost': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'settlement_period': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['internet.SettlementPeriod']", 'null': 'True', 'blank': 'True'}),
            'time_access_service': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['internet.TimeAccessService']", 'null': 'True', 'on_delete': 'models.SET_NULL', 'blank': 'True'}),
            'traffic_transmit_service': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['internet.TrafficTransmitService']", 'null': 'True', 'on_delete': 'models.SET_NULL', 'blank': 'True'}),
            'userblock_cost': ('django.db.models.fields.DecimalField', [], {'default': '0', 'max_digits': '30', 'decimal_places': '2', 'blank': 'True'}),
            'userblock_max_days': ('django.db.models.fields.IntegerField', [], {'default': '0', 'blank': 'True'}),
            'userblock_require_balance': ('django.db.models.fields.DecimalField', [], {'default': '0', 'max_digits': '10', 'decimal_places': '2', 'blank': 'True'}),
            'vpn_guest_ippool': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'tariff_guest_vpn_ippool_set'", 'null': 'True', 'on_delete': 'models.SET_NULL', 'to': u"orm['internet.IPPool']"}),
            'vpn_ippool': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'tariff_vpn_ippool_set'", 'null': 'True', 'on_delete': 'models.SET_NULL', 'to': u"orm['internet.IPPool']"})
        },
        u'internet.timeaccessservice': {
            'Meta': {'object_name': 'TimeAccessService', 'db_table': "'billservice_timeaccessservice'"},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'prepaid_time': ('django.db.models.fields.IntegerField', [], {'default': '0', 'blank': 'True'}),
            'reset_time': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'rounding': ('django.db.models.fields.IntegerField', [], {'default': '0', 'blank': 'True'}),
            'tarification_step': ('django.db.models.fields.IntegerField', [], {'default': '60', 'blank': 'True'})
        },
        u'internet.timeperiod': {
            'Meta': {'ordering': "['name']", 'object_name': 'TimePeriod', 'db_table': "'billservice_timeperiod'"},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'})
        },
        u'internet.traffictransmitservice': {
            'Meta': {'object_name': 'TrafficTransmitService', 'db_table': "'billservice_traffictransmitservice'"},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'reset_traffic': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        }
    }

    complete_apps = ['hotspot']